FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    libelf1 iproute2 ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY target/release/udp-fanout /opt/udp-fanout/udp-fanout
COPY target/udp-fanout-ebpf /opt/udp-fanout/udp-fanout-ebpf
COPY target/udp-fanout-ebpf-xdp /opt/udp-fanout/udp-fanout-ebpf-xdp
ENTRYPOINT ["/opt/udp-fanout/udp-fanout"]
CMD ["--config", "/etc/udp-fanout/config.yaml", "--xdp-program", "/opt/udp-fanout/udp-fanout-ebpf-xdp"]
